---
new_page_extension: md
auto_deploy: false
admin_path: "/"
webhook_url: 
collections: 
upload_dir: img
public_path: "/img"
front_matter_path: www.joyofprofessionallearning.org/img
use_front_matter_path: false
file_template: ":filename:"
