---
new_page_extension: md
auto_deploy: false
admin_path: www.joyofprofessionallearning.org/
webhook_url: 
collections: 
upload_dir: www.joyofprofessionallearning.org/img/blog-posts
public_path: www.joyofprofessionallearning.org/img/blog-posts
front_matter_path: www.joyofprofessionallearning.org/img/blog-posts
use_front_matter_path: false
file_template: ":filename:"
