---
upload_path: www.joyofprofessionallearning.org/img/blog-posts/
frontmatter_file_url_template: www.joyofprofessionallearning.org/img/blog-posts/
body_file_url_template: www.joyofprofessionallearning.org/img/blog-posts/
new_page_extension: md
auto_deploy: false
admin_path: www.joyofprofessionallearning.org/
webhook_url: 
collections: 
