---
upload_path: "/img/blog-posts/"
frontmatter_file_url_template: "/img/blog-posts/"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
collections: 
